In [2]:
# numpy is a library that allows for the use of arrays and matrices in python
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [4]:
type(a)

numpy.ndarray

- Basic Operation of array

In [5]:
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [6]:
# creating a 2D array
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [7]:
# creating a 3D array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


- Methods

In [8]:
print(b.shape) #(2,2,2) 2 arrays , 2 rows, 2 columns

(2, 2, 2)


In [9]:
print(a.ndim)

2


In [10]:
print(a.dtype)

int64


In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [13]:
np.random.randint(10,30, size=(3,3))

array([[12, 15, 13],
       [19, 29, 17],
       [15, 27, 10]], dtype=int32)

In [14]:
x = np.array([[7,2,3],
              [2,5,2,],
              [3,5,1]])

y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])

print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]
